export default [
	{ name: "John Deere (Deere & Company)", shortName: "John Deere", countryCode: "US", regionCode: "019" },
	{ name: "AGCO Corporation", shortName: "AGCO", countryCode: "US", regionCode: "019" },
	{ name: "CNH Industrial", shortName: "CNH", countryCode: "US", regionCode: "019" },
	{ name: "Case IH", shortName: "Case IH", countryCode: "US", regionCode: "019" },
	{ name: "New Holland Agriculture", shortName: "New Holland", countryCode: "US", regionCode: "019" },
	{ name: "Great Plains Manufacturing", shortName: "Great Plains", countryCode: "US", regionCode: "019" },
	{ name: "Kinze Manufacturing", shortName: "Kinze", countryCode: "US", regionCode: "019" },
	{ name: "Ag Leader Technology", shortName: "Ag Leader", countryCode: "US", regionCode: "019" },
	{ name: "Buhler Industries", shortName: "Buhler", countryCode: "US", regionCode: "019" },
	{ name: "Art's Way Manufacturing", shortName: "Art's Way", countryCode: "US", regionCode: "019" },
	{ name: "Unverferth Manufacturing", shortName: "Unverferth", countryCode: "US", regionCode: "019" },
	{ name: "Vermeer Corporation", shortName: "Vermeer", countryCode: "US", regionCode: "019" },
	{ name: "Alamo Group", shortName: "Alamo", countryCode: "US", regionCode: "019" },
	{ name: "Autonomous Solutions", shortName: "Autonomous Solutions", countryCode: "US", regionCode: "019" },
	{ name: "Yetter Farm Equipment", shortName: "Yetter", countryCode: "US", regionCode: "019" },
	{ name: "MacDon Industries", shortName: "MacDon", countryCode: "CA", regionCode: "019" },
	{ name: "Bourgault Industries", shortName: "Bourgault", countryCode: "CA", regionCode: "019" },
	{ name: "Morris Industries", shortName: "Morris", countryCode: "CA", regionCode: "019" },
	{ name: "Degelman Industries", shortName: "Degelman", countryCode: "CA", regionCode: "019" },
	{ name: "Salford Group", shortName: "Salford", countryCode: "CA", regionCode: "019" },
	{ name: "Versatile", shortName: "Versatile", countryCode: "CA", regionCode: "019" },
	{ name: "CLAAS KGaA mbH", shortName: "CLAAS", countryCode: "DE", regionCode: "150" },
	{ name: "Fendt", shortName: "Fendt", countryCode: "DE", regionCode: "150" },
	{ name: "Lemken", shortName: "Lemken", countryCode: "DE", regionCode: "150" },
	{ name: "Amazone", shortName: "Amazone", countryCode: "DE", regionCode: "150" },
	{ name: "Krone", shortName: "Krone", countryCode: "DE", regionCode: "150" },
	{ name: "Horsch", shortName: "Horsch", countryCode: "DE", regionCode: "150" },
	{ name: "Grimme", shortName: "Grimme", countryCode: "DE", regionCode: "150" },
	{ name: "Rauch", shortName: "Rauch", countryCode: "DE", regionCode: "150" },
	{ name: "Müthing", shortName: "Müthing", countryCode: "DE", regionCode: "150" },
	{ name: "SDF Group", shortName: "SDF", countryCode: "IT", regionCode: "150" },
	{ name: "Deutz-Fahr", shortName: "Deutz-Fahr", countryCode: "IT", regionCode: "150" },
	{ name: "SAME", shortName: "SAME", countryCode: "IT", regionCode: "150" },
	{ name: "Landini", shortName: "Landini", countryCode: "IT", regionCode: "150" },
	{ name: "Lamborghini Trattori", shortName: "Lamborghini", countryCode: "IT", regionCode: "150" },
	{ name: "Antonio Carraro", shortName: "Antonio Carraro", countryCode: "IT", regionCode: "150" },
	{ name: "Goldoni", shortName: "Goldoni", countryCode: "IT", regionCode: "150" },
	{ name: "BCS Group", shortName: "BCS", countryCode: "IT", regionCode: "150" },
	{ name: "Maschio Gaspardo", shortName: "Maschio Gaspardo", countryCode: "IT", regionCode: "150" },
	{ name: "Cosmo", shortName: "Cosmo", countryCode: "IT", regionCode: "150" },
	{ name: "ROC", shortName: "ROC", countryCode: "IT", regionCode: "150" },
	{ name: "Oliver Agro", shortName: "Oliver", countryCode: "IT", regionCode: "150" },
	{ name: "Valtra", shortName: "Valtra", countryCode: "FI", regionCode: "150" },
	{ name: "Kuhn Group", shortName: "Kuhn", countryCode: "FR", regionCode: "150" },
	{ name: "Grégoire Besson", shortName: "Grégoire Besson", countryCode: "FR", regionCode: "150" },
	{ name: "Sulky-Burel", shortName: "Sulky", countryCode: "FR", regionCode: "150" },
	{ name: "Grégoire", shortName: "Grégoire", countryCode: "FR", regionCode: "150" },
	{ name: "JCB", shortName: "JCB", countryCode: "GB", regionCode: "150" },
	{ name: "McCormick Tractors", shortName: "McCormick", countryCode: "GB", regionCode: "150" },
	{ name: "Massey Ferguson", shortName: "Massey Ferguson", countryCode: "GB", regionCode: "150" },
	{ name: "Vredo", shortName: "Vredo", countryCode: "NL", regionCode: "150" },
	{ name: "Lely", shortName: "Lely", countryCode: "NL", regionCode: "150" },
	{ name: "Kongskilde", shortName: "Kongskilde", countryCode: "DK", regionCode: "150" },
	{ name: "Dalbo", shortName: "Dalbo", countryCode: "DK", regionCode: "150" },
	{ name: "JF-Stoll", shortName: "JF-Stoll", countryCode: "DK", regionCode: "150" },
	{ name: "Väderstad", shortName: "Väderstad", countryCode: "SE", regionCode: "150" },
	{ name: "Pöttinger", shortName: "Pöttinger", countryCode: "AT", regionCode: "150" },
	{ name: "Steyr", shortName: "Steyr", countryCode: "AT", regionCode: "150" },
	{ name: "Hürlimann", shortName: "Hürlimann", countryCode: "AT", regionCode: "150" },
	{ name: "Ursus", shortName: "Ursus", countryCode: "PL", regionCode: "150" },
	{ name: "Pronar", shortName: "Pronar", countryCode: "PL", regionCode: "150" },
	{ name: "Krukowiak", shortName: "Krukowiak", countryCode: "PL", regionCode: "150" },
	{ name: "Belarus (MTZ)", shortName: "Belarus", countryCode: "BY", regionCode: "151" },
	{ name: "Zetor", shortName: "Zetor", countryCode: "CZ", regionCode: "150" },
	{ name: "Tumosan", shortName: "Tumosan", countryCode: "TR", regionCode: "145" },
	{ name: "Erkunt", shortName: "Erkunt", countryCode: "TR", regionCode: "145" },
	{ name: "Hattat", shortName: "Hattat", countryCode: "TR", regionCode: "145" },
	{ name: "Kverneland Group", shortName: "Kverneland", countryCode: "NO", regionCode: "154" },
	{ name: "Vicon", shortName: "Vicon", countryCode: "NO", regionCode: "154" },
	{ name: "Joskin", shortName: "Joskin", countryCode: "BE", regionCode: "150" },
	{ name: "Rostelmash", shortName: "Rostelmash", countryCode: "RU", regionCode: "151" },
	{ name: "Kirovets", shortName: "Kirovets", countryCode: "RU", regionCode: "151" },
	{ name: "Kubota Corporation", shortName: "Kubota", countryCode: "JP", regionCode: "030" },
	{ name: "Yanmar", shortName: "Yanmar", countryCode: "JP", regionCode: "030" },
	{ name: "Iseki", shortName: "Iseki", countryCode: "JP", regionCode: "030" },
	{ name: "Mitsubishi Agricultural Machinery", shortName: "Mitsubishi Agri", countryCode: "JP", regionCode: "030" },
	{ name: "Hinomoto", shortName: "Hinomoto", countryCode: "JP", regionCode: "030" },
	{ name: "YTO Group", shortName: "YTO", countryCode: "CN", regionCode: "030" },
	{ name: "Lovol", shortName: "Lovol", countryCode: "CN", regionCode: "030" },
	{ name: "Changzhou Dongfeng (DFAM)", shortName: "Dongfeng", countryCode: "CN", regionCode: "030" },
	{ name: "Shandong Shifeng", shortName: "Shifeng", countryCode: "CN", regionCode: "030" },
	{ name: "Wuzheng Group", shortName: "Wuzheng", countryCode: "CN", regionCode: "030" },
	{ name: "China National Machinery Industry Corporation", shortName: "CNMIC", countryCode: "CN", regionCode: "030" },
	{ name: "Mahindra & Mahindra", shortName: "Mahindra", countryCode: "IN", regionCode: "034" },
	{ name: "TAFE", shortName: "TAFE", countryCode: "IN", regionCode: "034" },
	{ name: "Escorts Limited", shortName: "Escorts", countryCode: "IN", regionCode: "034" },
	{ name: "Sonalika", shortName: "Sonalika", countryCode: "IN", regionCode: "034" },
	{ name: "VST Tillers Tractors", shortName: "VST", countryCode: "IN", regionCode: "034" },
	{ name: "Preet Group", shortName: "Preet", countryCode: "IN", regionCode: "034" },
	{ name: "Swaraj Tractors", shortName: "Swaraj", countryCode: "IN", regionCode: "034" },
	{ name: "Fieldking", shortName: "Fieldking", countryCode: "IN", regionCode: "034" },
	{ name: "Daedong (Kioti)", shortName: "Kioti", countryCode: "KR", regionCode: "030" },
	{ name: "LS Mtron", shortName: "LS Mtron", countryCode: "KR", regionCode: "030" },
	{ name: "TYM Tractors", shortName: "TYM", countryCode: "KR", regionCode: "030" },
	{ name: "Millat Tractors", shortName: "Millat", countryCode: "PK", regionCode: "034" },
	{ name: "Al-Ghazi Tractors", shortName: "Al-Ghazi", countryCode: "PK", regionCode: "034" },
	{ name: "Stara", shortName: "Stara", countryCode: "BR", regionCode: "005" },
	{ name: "Jacto", shortName: "Jacto", countryCode: "BR", regionCode: "005" },
	{ name: "Marchesan", shortName: "Marchesan", countryCode: "BR", regionCode: "005" },
	{ name: "Baldan", shortName: "Baldan", countryCode: "BR", regionCode: "005" },
	{ name: "Montana", shortName: "Montana", countryCode: "BR", regionCode: "005" },
	{ name: "Semeato", shortName: "Semeato", countryCode: "BR", regionCode: "005" },
	{ name: "Agrale", shortName: "Agrale", countryCode: "BR", regionCode: "005" },
	{ name: "Agriculte", shortName: "Agriculte", countryCode: "BR", regionCode: "005" },
	{ name: "Jumil", shortName: "Jumil", countryCode: "BR", regionCode: "005" },
	{ name: "Pauny", shortName: "Pauny", countryCode: "AR", regionCode: "005" },
	{ name: "Crucianelli", shortName: "Crucianelli", countryCode: "AR", regionCode: "005" },
	{ name: "Apache", shortName: "Apache", countryCode: "AR", regionCode: "005" },
	{ name: "Goscor", shortName: "Goscor", countryCode: "ZA", regionCode: "002" },
	{ name: "Horwood Bagshaw", shortName: "Horwood Bagshaw", countryCode: "AU", regionCode: "009" },
	{ name: "Simplicity", shortName: "Simplicity", countryCode: "AU", regionCode: "009" },
	{ name: "K-Line Agriculture", shortName: "K-Line", countryCode: "AU", regionCode: "009" },
	{ name: "Kanga Farm Equipment", shortName: "Kanga", countryCode: "AU", regionCode: "009" },
	{ name: "Dobmac Agricultural Machinery", shortName: "Dobmac", countryCode: "AU", regionCode: "009" },
	{ name: "Southern Cross Ag Machinery", shortName: "Southern Cross", countryCode: "AU", regionCode: "009" },
	{ name: "TTQ", shortName: "TTQ", countryCode: "AU", regionCode: "009" },
	{ name: "Hustler Equipment", shortName: "Hustler", countryCode: "NZ", regionCode: "009" },
	{ name: "Giltrap", shortName: "Giltrap", countryCode: "NZ", regionCode: "009" },
	{ name: "Duncan Ag", shortName: "Duncan Ag", countryCode: "NZ", regionCode: "009" },
	{ name: "Fencepro", shortName: "Fencepro", countryCode: "NZ", regionCode: "009" },
	{ name: "Farmgear", shortName: "Farmgear", countryCode: "NZ", regionCode: "009" }
]